version: "3"
services:
  schema-registry-db:
    container_name: avroschemaregistry_schema-registry-db_1
    image: postgres:9.6.8
    volumes:
      - $HOME/postgresql/9.6/data/schema-registry:/var/lib/postgresql/data:delegated

  schema-registry-web:
    container_name: avroschemaregistry_schema-registry-web_1
    build: .
    depends_on:
      - schema-registry-db
    command: "bin/start"
    ports:
      - "21004:21004"
    environment:
      POSTGRES_HOST: schema-registry-db
      POSTGRES_USER: postgres
    volumes:
      - .:/usr/src/app
      - bundle-volume:/usr/src/bundler:delegated

volumes:
  bundle-volume:

networks:
  default:
    external:
      name: ezcater-development-network
