name: avro-schema-registry
slack: pb-s-service-car

staging:
  environment:
    RACK_ENV: staging
    RAILS_ENV: staging
production:
  environment:
    RACK_ENV: production
    RAILS_ENV: production
deployables:
  web:
    type: web
    port: 3000
    command: "bundle exec rails server -p 3000 -b 0.0.0.0"
    replicas: 3
    health_check_path: "/health_check"
    staging:
      host: "asr.staging-ezcater.com"
    production:
      host: "asr.ezcater.com"
  webcompat:
    type: web
    port: 3000
    command: "bundle exec rails server -p 3000 -b 0.0.0.0"
    replicas: 2
    health_check_path: "/health_check"
    staging:
      host: "asr-compat.staging-ezcater.com"
      environment:
        READ_ONLY_MODE: true
    production:
      host: "asr-compat.ezcater.com"
      environment:
        READ_ONLY_MODE: true

tests:
  primary:
    - name: avro-schema-registry
      build: .
      environment:
        POSTGRES_HOST: localhost
        POSTGRES_USER: ezcater
        PORT: 3000
  services:
    - name: postgres
      image: postgres:9.6.8
      environment:
        POSTGRES_USER: ezcater
        POSTGRES_DB: avro-schema-registry_test
  steps:
    - run:
        test: rubocop
        command: bundle exec rubocop
    - run:
        test: rspec
        command: bundle exec rspec
