version: 2

jobs:
  build:
    working_directory: /dev/shm/ezcater
    docker:
      - image: ezcater/circleci:2.4.1-b
        auth:
          username: ezcircleci
          password: $DOCKER_HUB_PASSWORD
        environment:
          CIRCLE_CI: true
          RACK_ENV: test
          RAILS_ENV: test
          DATABASE_URL: postgres://localhost/circle_ruby_test
          POSTGRES_HOST: localhost
          PGHOST: 127.0.0.1
          LC_ALL: C
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_ruby_test
    steps:
      - checkout
      - run: ln -s /home/circleci/ezcater/vendor vendor
      - restore_cache:
          keys:
            - ruby-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile" }}
            - ruby-cache-{{ arch }}-{{ .Branch }}-
            - ruby-cache-{{ arch }}-
      - run: bundle check --path=/home/circleci/ezcater/vendor/bundle || bundle install --path=/home/circleci/ezcater/vendor/bundle --jobs=4 --retry=3
      - run: bundle clean --force
      - save_cache:
          key: ruby-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile" }}
          paths:
            - /home/circleci/ezcater/tmp/cache
            - /home/circleci/ezcater/vendor/bundle
      - run: bundle exec rubocop
      - run: bundle exec rake db:create db:schema:load
      - run:
          command: |
            bundle exec rspec --format progress
      - store_artifacts:
          path: log/test.log
      - store_artifacts:
          path: test_results/rspec.xml
      - store_test_results:
          path: test_results
